Reverting "fflog-errors: new helper" to per-segment check
The segments are not independent: I tried to corrupt one .m4s segment in
a particularly bad way, and ffmpeg propagated the error to the following
segments, basically to the end of the stream.

diff --git a/wget-hls b/wget-hls
--- a/wget-hls
+++ b/wget-hls
@@ -167,6 +167,14 @@ wGetParts()
 	return $rc
 }
 
+FixupExamLog()
+{
+	sed -i 's/\r/\n/g' "$1"
+	sed -ni '/\w/p' "$1"
+	time=$(sed -n '$s/^\(frame\|size\)=.* time=\([^ ]\+\) .*/\2/p' "$1")
+	sed -i '/^\(frame\|size\)=.* time=/d' $1
+}
+
 OUT=
 time=
 type=
@@ -242,30 +250,41 @@ wGetHLS()
 			return 1
 		fi
 	fi
+	ffexam=(nice -5 ffmpeg -xerror -v warning -stats)
+	if [ "$type" = dash ]; then
+	    ffexam+=(-allowed_extensions ALL)
+	fi
 	rc=
-	nice -5 ffmpeg -hide_banner -nostats -i "$OUT" -f null - &>$tmpdir/fferr || rc=1
-	time=$("$av0dir"/fflog-errors $tmpdir/fferr) || rc=1
+	"${ffexam[@]}" -i "$OUT" -f null - &>$tmpdir/fferr || rc=1
+	FixupExamLog $tmpdir/fferr
 	tolera='non-existing SPS 0 referenced in buffering period
 SPS unavailable in decode_picture_timing
 Application provided invalid, non.monotonically increasing dts to muxer
 Invalid timestamps stream=
 Last message repeated'
-	if grep -q -v "$tolera" $tmpdir/fferr; then
+	if grep -v "$tolera" $tmpdir/fferr >$tmpdir/baderr || [ -n "$rc" ]; then
 		echo >&2 "${0##*/}: rechecking"
-	elif [ -n "$rc" ]; then
-		# too bad, ffmpeg fails even without -xerror,
-		# and we don't have any errors to recheck
-		cat $tmpdir/fferr
-		echo "${0##*/}: cannot proceed"
-		return 1
 	else
 		return 0
 	fi >&2
-	if [ -n "$type" ]; then
-		n=$(wc -l <$tmpdir/parts)
-		cat <$tmpdir/fferr >$tmpdir/parts.all-errors
+	if [ "$type" = hls ]; then
+		local n=0
+		while read -r part; do
+			f=${part##*/}
+			if ! [ -s "$f" ]; then
+				echo >&2 "${0##*/}: missing $f (cannot happen)"
+				false
+			fi
+			"${ffmpeg[@]}" -v warning -i "$f" -f null - 2>&1 </dev/null |
+				stdbuf -oL sed "s|\t| |g;s|^|${part//|/\\|}\t|" &
+			(( ++n < 2 )) || wait -n
+		done <$tmpdir/parts >$tmpdir/parts.all-errors
+		wait
 		# if some error is encountered in more than half of the parts,
 		# it's not a real error
+		perl -pi -e 's/ @ 0x[0-9a-f]+\]/]/' $tmpdir/parts.all-errors
+		perl -pi -e 's/\b(pts|dts|size)=\d+\b/$1=42/g' $tmpdir/parts.all-errors
+		perl -pi -e 's/\b(dts to muxer in stream \d): \d+ >= \d+/$1/' $tmpdir/parts.all-errors
 		sort -t$'\t' -u -k2,2 -k1,1 -o $tmpdir/parts.all-errors{,}
 		cut -f2 $tmpdir/parts.all-errors |uniq -c |
 			awk -v n=$n '(n==1||$1<=n/2){sub(" +[0-9]+ ","");print}' |
@@ -282,8 +301,8 @@ Last message repeated'
 		DoubleCheck "$1" "$OUT"
 	fi
 	rc=
-	nice -5 ffmpeg -xerror -hide_banner -nostats -i "$OUT" -f null - &>$tmpdir/fferr || rc=1
-	time=$("$av0dir"/fflog-errors $tmpdir/fferr) || rc=1
+	"${ffexam[@]}" -i "$OUT" -f null - &>$tmpdir/fferr || rc=1
+	FixupExamLog $tmpdir/fferr
 	# stream still corrupted?
 	if grep -v "$tolera" $tmpdir/fferr; then
 		echo "${0##*/}: cannot proceed"
